---
version: '3'
services:
    nginx:
      build:
        context: build/
      ports:
        - "8080:8080"
    db:
      image: postgres:12
      container_name: db
      restart: always
      volumes:
        - /opt/data/bases:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: secret
        POSTGRES_USER: dbuser
        POSTGRES_DB: wedos
      ports:
        - "5432:5432"
    nginx-exporter:
      image: nginx/nginx-prometheus-exporter:0.10.0
      container_name: nginx-exporter
      restart: unless-stopped
      environment:
        - SCRAPE_URI=http://3.84.32.96:8080/nginx_status
      ports:
        - "9113:9113"

volumes:
  data:
    name: data
